### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by erwinpaillacan** [titu1994/keras-mobile-colorizer#1]
I'm trying to train but Python give a error:
``Exception ignored in: <generator object val_batch_generator at 0x7f88b80d8f68>
Traceback (most recent call last):
  File "/media/erwin/Data/lamem/keras-mobile-colorizer/data_utils.py", line 263, in val_batch_generator
    yield ([l, features], ab)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1547, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5231, in get_controller
    context.context().context_switches.pop()
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 141, in pop
    self.stack.pop()
IndexError: pop from empty list
Exception ignored in: <generator object train_generator at 0x7f88b80d8f10>
Traceback (most recent call last):
  File "/media/erwin/Data/lamem/keras-mobile-colorizer/data_utils.py", line 246, in train_generator
    yield ([l, features], ab)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1547, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5231, in get_controller
    context.context().context_switches.pop()
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 141, in pop
    self.stack.pop()
IndexError: pop from empty list  ``

**Comment by titu1994** [comment]
Seemed your validatuj dataset is empty for some reason. Parhaos wrong path?

**Comment by erwinpaillacan** [comment]
I have the correct path of the TFrecord's.  This is the output:

`/home/erwin/anaconda3/envs/tf/bin/python /media/erwin/Data/lamem/keras-mobile-colorizer/train_mobilenet.py
2018-12-05 15:38:36.720344: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
2018-12-05 15:38:36.829387: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:964] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-12-05 15:38:36.829709: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1411] Found device 0 with properties: 
name: GeForce GTX 1060 with Max-Q Design major: 6 minor: 1 memoryClockRate(GHz): 1.3415
pciBusID: 0000:01:00.0
totalMemory: 2.95GiB freeMemory: 2.87GiB
2018-12-05 15:38:36.829719: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-12-05 15:38:37.060479: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-05 15:38:37.060501: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-12-05 15:38:37.060506: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-12-05 15:38:37.060602: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2576 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1)
Using TensorFlow backend.
/media/erwin/Data/lamem/keras-mobile-colorizer
Colorization model built and compiled
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
==================================================================================================
input_1 (InputLayer)            (None, 128, 128, 1)  0                                            
__________________________________________________________________________________________________
conv2d_1 (Conv2D)               (None, 64, 64, 64)   640         input_1[0][0]                    
__________________________________________________________________________________________________
conv2d_2 (Conv2D)               (None, 64, 64, 128)  73856       conv2d_1[0][0]                   
__________________________________________________________________________________________________
conv2d_3 (Conv2D)               (None, 32, 32, 128)  147584      conv2d_2[0][0]                   
__________________________________________________________________________________________________
conv2d_4 (Conv2D)               (None, 32, 32, 256)  295168      conv2d_3[0][0]                   
__________________________________________________________________________________________________
conv2d_5 (Conv2D)               (None, 16, 16, 256)  590080      conv2d_4[0][0]                   
__________________________________________________________________________________________________
conv2d_6 (Conv2D)               (None, 16, 16, 512)  1180160     conv2d_5[0][0]                   
__________________________________________________________________________________________________
input_2 (InputLayer)            (None, 1000)         0                                            
__________________________________________________________________________________________________
conv2d_7 (Conv2D)               (None, 16, 16, 512)  2359808     conv2d_6[0][0]                   
__________________________________________________________________________________________________
repeat_vector_1 (RepeatVector)  (None, 256, 1000)    0           input_2[0][0]                    
__________________________________________________________________________________________________
conv2d_8 (Conv2D)               (None, 16, 16, 256)  1179904     conv2d_7[0][0]                   
__________________________________________________________________________________________________
reshape_1 (Reshape)             (None, 16, 16, 1000) 0           repeat_vector_1[0][0]            
__________________________________________________________________________________________________
concatenate_1 (Concatenate)     (None, 16, 16, 1256) 0           conv2d_8[0][0]                   
                                                                 reshape_1[0][0]                  
__________________________________________________________________________________________________
conv2d_9 (Conv2D)               (None, 16, 16, 256)  321792      concatenate_1[0][0]              
__________________________________________________________________________________________________
conv2d_10 (Conv2D)              (None, 16, 16, 128)  295040      conv2d_9[0][0]                   
__________________________________________________________________________________________________
up_sampling2d_1 (UpSampling2D)  (None, 32, 32, 128)  0           conv2d_10[0][0]                  
__________________________________________________________________________________________________
concatenate_2 (Concatenate)     (None, 32, 32, 256)  0           up_sampling2d_1[0][0]            
                                                                 conv2d_3[0][0]                   
__________________________________________________________________________________________________
conv2d_11 (Conv2D)              (None, 32, 32, 64)   147520      concatenate_2[0][0]              
__________________________________________________________________________________________________
conv2d_12 (Conv2D)              (None, 32, 32, 64)   36928       conv2d_11[0][0]                  
__________________________________________________________________________________________________
up_sampling2d_2 (UpSampling2D)  (None, 64, 64, 64)   0           conv2d_12[0][0]                  
__________________________________________________________________________________________________
concatenate_3 (Concatenate)     (None, 64, 64, 128)  0           up_sampling2d_2[0][0]            
                                                                 conv2d_1[0][0]                   
__________________________________________________________________________________________________
conv2d_13 (Conv2D)              (None, 64, 64, 32)   36896       concatenate_3[0][0]              
__________________________________________________________________________________________________
conv2d_transpose_1 (Conv2DTrans (None, 128, 128, 2)  1026        conv2d_13[0][0]                  
==================================================================================================
Total params: 6,666,402
Trainable params: 6,666,402
Non-trainable params: 0
__________________________________________________________________________________________________
Epoch 1/5
2018-12-05 15:38:41.605047: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1490] Adding visible gpu devices: 0
2018-12-05 15:38:41.605105: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-12-05 15:38:41.605115: I tensorflow/core/common_runtime/gpu/gpu_device.cc:977]      0 
2018-12-05 15:38:41.605123: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] 0:   N 
2018-12-05 15:38:41.605267: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1103] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2576 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 with Max-Q Design, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-12-05 15:38:43.959689: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.01GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-12-05 15:38:44.247457: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.54GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-12-05 15:38:44.494533: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.33GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-12-05 15:38:44.755023: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.65GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-12-05 15:38:44.782038: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.58GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-12-05 15:38:44.929172: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.58GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-12-05 15:38:45.213192: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.10GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-12-05 15:38:45.213230: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 1.52GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-12-05 15:38:45.366642: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.20GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.
2018-12-05 15:38:45.366679: W tensorflow/core/common_runtime/bfc_allocator.cc:215] Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.49GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available.

1/4 [======>.......................] - ETA: 19s - loss: 843644.0625 - y_true_max: 0.7439 - y_true_min: -0.5586 - y_pred_max: 0.7370 - y_pred_min: -0.8656
2/4 [==============>...............] - ETA: 7s - loss: 1722728.6562 - y_true_max: 0.7293 - y_true_min: -0.6367 - y_pred_max: 0.7263 - y_pred_min: -0.8747
3/4 [=====================>........] - ETA: 2s - loss: 1461270.0417 - y_true_max: 0.7164 - y_true_min: -0.6746 - y_pred_max: 0.6473 - y_pred_min: -0.8036Traceback (most recent call last):
  File "/media/erwin/Data/lamem/keras-mobile-colorizer/train_mobilenet.py", line 32, in <module>
    validation_steps=1
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/keras/engine/training_generator.py", line 234, in fit_generator
    workers=0)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/keras/engine/training.py", line 1472, in evaluate_generator
    verbose=verbose)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/keras/engine/training_generator.py", line 330, in evaluate_generator
    generator_output = next(output_generator)
StopIteration
Exception ignored in: <generator object train_generator at 0x7fb0c14f8e60>
Traceback (most recent call last):
  File "/media/erwin/Data/lamem/keras-mobile-colorizer/data_utils.py", line 255, in train_generator
    yield ([l, features], ab)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1547, in __exit__
    self._default_graph_context_manager.__exit__(exec_type, exec_value, exec_tb)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5231, in get_controller
    context.context().context_switches.pop()
  File "/home/erwin/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow/python/eager/context.py", line 141, in pop
    self.stack.pop()
IndexError: pop from empty list`

**Comment by erwinpaillacan** [comment]
Always died in the last call:

1/10 [==>...........................] - ETA: 58s - loss: 2884735.7500 - y_true_max: 0.7439 - y_true_min: -0.5586 - y_pred_max: 0.8873 - y_pred_min: -0.8469
 2/10 [=====>........................] - ETA: 28s - loss: 18625775.8750 - y_true_max: 0.7298 - y_true_min: -0.6952 - y_pred_max: 0.8910 - y_pred_min: -0.8753
 3/10 [========>.....................] - ETA: 17s - loss: 12424550.3405 - y_true_max: 0.7277 - y_true_min: -0.7407 - y_pred_max: 0.6968 - y_pred_min: -0.6971
 4/10 [===========>..................] - ETA: 12s - loss: 9327076.6675 - y_true_max: 0.7247 - y_true_min: -0.7364 - y_pred_max: 0.6145 - y_pred_min: -0.5918 
 5/10 [==============>...............] - ETA: 8s - loss: 7470580.3027 - y_true_max: 0.7179 - y_true_min: -0.7392 - y_pred_max: 0.5859 - y_pred_min: -0.5408 
 6/10 [=================>............] - ETA: 6s - loss: 6241725.9840 - y_true_max: 0.7152 - y_true_min: -0.7091 - y_pred_max: 0.5681 - y_pred_min: -0.5202
 7/10 [====================>.........] - ETA: 4s - loss: 5357208.4450 - y_true_max: 0.7138 - y_true_min: -0.7150 - y_pred_max: 0.5464 - y_pred_min: -0.5025
 8/10 [=======================>......] - ETA: 2s - loss: 4692467.5334 - y_true_max: 0.7176 - y_true_min: -0.7150 - y_pred_max: 0.5224 - y_pred_min: -0.4867
 9/10 [==========================>...] - ETA: 1s - loss: 4173811.9017 - y_true_max: 0.7183 - y_true_min: -0.7056 - y_pred_max: 0.5060 - y_pred_min: -0.4726T




erroooooooooor

**Comment by erwinpaillacan** [comment]
I solve!
I have another question: How about the model? we are re-train mobilenet_model_h.h5 in mobilenet_model_v2.h5?

**Comment by titu1994** [comment]
You can try changing the model, but you might need to change the number of output filters after global average pooling.

**Comment by Xiaocong6** [comment]
Hi, I met the same error. How do you solve it?
Hope for your help!
Thanks!

**Comment by wudejian789** [comment]
> I solve!
> I have another question: How about the model? we are re-train mobilenet_model_h.h5 in mobilenet_model_v2.h5?

Hi, I met the same problem, too. 
Could you please tell me how to solve it?
Thanks!
